version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-spring
    environment:
      MYSQL_ROOT_PASSWORD: Matheus37420!
      MYSQL_DATABASE: bdfabrica
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql

volumes:
  mysql-data:

networks:
  spring-mysql:
